version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18
    working_directory: ~/repo

jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Prettier on Project Sources
          command: |
            npx prettier --check .

  build:
    executor: node-executor
    parameters:
      project_name:
        type: string
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd << parameters.project_name >>
            npm install
      - run:
          name: Build Angular Project
          command: |
            cd << parameters.project_name >>
            npm run build -- --prod

workflows:
  version: 2
  build-and-lint:
    jobs:
      - lint
      - build:
          matrix:
            parameters:
              project_name: ["02-essentials", "02-essentials-ngmodule", "04-practice", "05-debugging", "06-components", "06-custom-2way-binding", "07-directives"]
